### ISSUE TITLE
Can not download pretrained model 

### ISSUE THREAD

**Issue by daisuke-sato-arithmer** [crockwell/partial_humans#1]
Following the instruction at `README.md`, I tried to download the pretrained file:
```
wget http://megaflop.eecs.umich.edu:8888/~cnris/partial_humans_website/crockwell.github.io/cmr/models.tar.gz && tar -xf models.tar.gz
```
Then it failed because of timeout.
I would be grateful if there is any problem in downloading model with the command above.
Thank you!

**Comment by crockwell** [comment]
Thanks for bringing this up -- please try again now (I edited the link in the README)

**Comment by daisuke-sato-arithmer** [comment]
I could download the files.
Thank you so much!

I will close this issue.

**Comment by maxsnap** [comment]
Hello Chris, it seems the pretrained model not available again. Could you kindly update the following links? Thank you! 

http://fouheylab.eecs.umich.edu/~cnris/partial_humans/hmr/models.tar.gz
http://fouheylab.eecs.umich.edu:/~cnris/partial_humans/cmr/models.tar.gz
