### ISSUE TITLE
About the training data and code

### ISSUE THREAD

**Issue by JosephKKim** [crockwell/partial_humans#2]
Hello, I have found your work recently. It seems like very interesting work which is dealing with the in-the-wild data.
However, briefly scanning this repository, it seems like there is no training code for this work. 
Is there any reason for not revealing the training code this work?

Thanks, 
Joseph.

**Comment by crockwell** [comment]
Hi Joseph,

Thanks! Yeah, sadly the training code was based on the HMR repo which uses Python 2 and Tensorflow so it was kind of a pain to use and pretty messy. So I did not release this code. Your best starting point would probably be the HMR code, from which you could change dataloading to crop based on keypoints. But it would take some time. 

Best,
Chris

**Comment by yuchen-ji** [comment]
Could you provide some details about the data augmentation of image croping, such as the scale of the cropped image(which keypoints should to be cropped), and when the cropped image will be added to train?

Thanks

**Comment by crockwell** [comment]
Hey - I think section 1.3 and 1.4 of the supplemental have these details you're asking for. If something still isn't clear, feel free to follow up!

**Comment by yuchen-ji** [comment]
Thanks，I noticed that it solved my problem!
